model_path:
model_name:

data:
  common:
    batch_size: 256
    num_workers: 4
    shuffle: False
    drop_last: False

    data_path: /workspace
    max_seq_len: 64

    eval_transforms:
      - _name: "" # base transform, key for image data in dataset will just be "image", "<_name>_image" otherwise
        pretraining: True
        size: 224
    
    text_token_mask_prob: 0.0

  datamodules:
    COCOCaptions: {}
    Flickr30K: {}
